<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <Content Include="Dialogue\**">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
  </ItemGroup>

	<ItemGroup>
		<Content Include="Music\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Sfx\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetCoreAudio" Version="2.0.0" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TerribleDialogue\TerribleDialogue.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Music\" />
  </ItemGroup>

</Project>
